### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-xmpp#1]
There's basically nothing in README except for a quick description of the repo. From the code it looks like one can use JSDoc to build documentation?

Anyway, would be good to have a bit more info in there, because right now it's basically impossible to know how to get started.

**Comment by silverbucket** [comment]
Added `jsdoc-to-markdown` and an `npm run doc` directive that will build an API.md, which is checked in now to the repo. So the existing jsdoc can now be more easily viewed and linked to. Will update the main sockethub wiki to link to each respective platforms API.md.
https://github.com/sockethub/sockethub-platform-xmpp/commit/56a547c58c23670f6cf0ac3707556376de2230ba

**Comment by skddc** [comment]
Honestly sorry to say, but: although this might document the internals for Sockethub developers, I don't see how that documents the actual usage for app developers. When I generated those docs myself this weekend in order to implement XMPP in Hyperchannel, I was actually *more* confused and tried to use it all wrong as a result of it.

Example: as an app developer, you're not actually using the `connect` function with that callback, and you can't emit a `connect` job. You also don't instantiate that XMPP class, so there's no way to call e.g. [update](https://github.com/sockethub/sockethub-platform-xmpp/blob/master/API.md#xmppupdatejob) with those example params.

I think the docs that app developers need are likely just different than the API docs for internals, that Sockethub developers can benefit from.

**Comment by silverbucket** [comment]
@skddc true, any suggestions for how to manage these differences with the least amount of duplication or scattered docs? The content of the AS objects as described in the API docs are useful for app developers, it's just the delivery context that's different. (In a web app you're using the AS object to send/receive the JSON but the data you send and receive is essentially the same).

**Comment by skddc** [comment]
I think some duplication is fine. The best place to document usage seperate from code comments would be the main Sockethub wiki imo. That's also where the missing general-usage pages are already linked.

**Comment by skddc** [comment]
... yay, I just saw https://github.com/sockethub/sockethub/wiki/Using-Platforms exists now. :)

**Comment by silverbucket** [comment]
@skddc that's easy for you to say, you're not the one who would be writing two sets of the same documentation. :)
I guess I'll just figure something out on my own then.

**Comment by silverbucket** [comment]
I created a Sockethub Client page which explains getting started with the sockethub client, including creating Activity Objects and setting credentials, then for other uses of the platforms it points to this API.md file which details each of the JSON structures for each type of action. I removed the params doc as that seemed to confuse you, so no references to callback anymore. Just method names, and the JSON it uses.

**Comment by skddc** [comment]
Great!

![thanks](https://cloud.githubusercontent.com/assets/842/25371561/ad973db6-2991-11e7-8ca4-f8032713cf32.gif)

**Comment by skddc** [comment]
I just looked into rendering JSON schema, because I was wondering if it makes sense to create schemas for the various AS objects (not just credentials), and stumbled upon MSON, which looks neat (basically JSON in Markdown):

https://help.apiary.io/api_101/json-schema/#mson-example
https://github.com/apiaryio/mson/blob/master/MSON%20Specification.md

Just putting this here as a note/inspiration.
