### ISSUE TITLE
Error: invalid property: "userName"

### ISSUE THREAD

**Issue by skddc** [sockethub/sockethub-platform-xmpp#2]
Trying to create the actor object from the example results in a schema error:

`Error: invalid property: "userName"`

**Comment by silverbucket** [comment]
Is this still a valid issue? Where did `userName` come from? It's not in the `xmpp` example, not sure what you're referencing, and with invalid properties, its good that you got back an error message. There was no failure of the system anywhere, right? If not, please close the issue.

**Comment by silverbucket** [comment]
Oops I closed it, well, I guess re-open if I'm missing something but this seems to just be a bad property name.

**Comment by skddc** [comment]
The example is from the API doc: https://github.com/sockethub/sockethub-platform-xmpp/blob/master/index.js#L80

**Comment by silverbucket** [comment]
ah, that shouldn't be there. removed.
