### ISSUE TITLE
Error "missing `listeners` object property" when trying to connect to server

### ISSUE THREAD

**Issue by galfert** [sockethub/sockethub-platform-xmpp#8]
When trying to connect to an XMPP server in Hyperchannel, using the PR https://github.com/67P/hyperchannel/pull/112 and Sockethub version 1.2.1, I get a SH failure message for the `connect`:

```js
{
    "@type": "connect",
    "actor": {
        "@id": "garret@5apps.com/hyperchannel",
        "@type": "person",
        "displayName": "garret"
    },
    "context": "xmpp",
    "error": "missing `listeners` object property"
}
```

Here's the log from Sockethub:

```
 sockethub:core:UaR2-zeduYE_n_xtAAAC credentials encrypted and saved to garret@5apps.com/hyperchannel +1ms
  sockethub:worker:UaR2-zeduYE_n_xtAAAC got job: connect 57ssDrjpWvu53uJp +2ms
  sockethub:worker:UaR2-zeduYE_n_xtAAAC creating new platform instance of xmpp for UaR2-zeduYE_n_xtAAAC +0ms
  sockethub:worker:UaR2-zeduYE_n_xtAAAC:xmpp calling: connect +2ms
  redis-connection-pool selecting database 0 +1ms
  redis-connection-pool 2. selected database: 0 +6ms
  sockethub:worker:UaR2-zeduYE_n_xtAAAC:xmpp:module got config for garret@5apps.com/hyperchannel +1ms
  connection-manager no record found with id: garret@5apps.com/hyperchannel +1ms
  sockethub:worker:UaR2-zeduYE_n_xtAAAC:xmpp:module creating client manager record. +0ms
  sockethub:core failed job: 22 missing `listeners` object property +5ms
  sockethub:core job [22] failed for socket UaR2-zeduYE_n_xtAAAC +5ms
  socket.io:client writing packet {"type":2,"data":["failure",{"@type":"connect","context":"xmpp","actor":{"@id":"garret@5apps.com/hyperchannel","@type":"person","displayName":"garret"},"error":"missing `listeners` object property"}],"nsp":"/"} +30ms
```

**Comment by silverbucket** [comment]
I fixed this last night, maybe a couple hours before you filed this :) The latest code should have no issues with this.
https://github.com/sockethub/sockethub-platform-xmpp/commit/31bcf88203ac2b6c17431fa911885b89b99218b7

**Comment by galfert** [comment]
Oh, I only saw you tagging Sockethub itself with 2.x and saw a commit message saying something about possibly breaking things. So I was hesitant to update and stayed at the latest 1.x version :)

I will try with latest master version then.

**Comment by silverbucket** [comment]
@galfert 2.x has been very stable for me so far

**Comment by galfert** [comment]
@silverbucket protip: when you don't adhere to git commit message line restrictions, you might get accidental swear words ;)

![its_ass](https://cloud.githubusercontent.com/assets/843/25893944/3956a1ea-357a-11e7-96a1-bad0ad1d8964.png)

**Comment by skddc** [comment]
We have some useful tips reg. commit messages over here: https://github.com/remotestorage/remotestorage.js/blob/stable/CONTRIBUTING.md#commit-messages

**Comment by skddc** [comment]
... should also add a note there about using seperate lines for refs, which worked great so far. Example: https://github.com/67P/hyperchannel/commit/825d26067fbbb639e76b9e54da7549d4809f7854

**Comment by silverbucket** [comment]
@skddc thanks for the tips. I need to get better about this and slow down sometimes.
